title: Holopin Badge
logo: public/images/holopin-logo.png
favicon: public/images/favicon.ico
description: Get yourself a Holopin README Badge to show your collection of badges.
show_downloads: false
theme: jekyll-theme-minimal
